# Generated by Django 3.1.3 on 2020-11-12 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insecuremail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
